# Generated by Django 3.0.6 on 2020-05-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PST', 'Pasta'), ('PZA', 'Pizza'), ('SUB', 'Sandwiches'), ('PLT', 'Platters'), ('SLD', 'Salads')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CheesesteakTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MSH', 'Mushrooms'), ('GPP', 'Green Peppers'), ('ONS', 'Onions')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('priceSmall', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('priceLarge', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('pizzaStyle', models.CharField(blank=True, choices=[('NML', 'Normal'), ('SCL', 'Sicilian')], max_length=3)),
                ('pizzaToppingsCount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('CanadianBacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('TomatoBasil', 'Tomato & Basil'), ('GreenPeppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('BuffaloChicken', 'Buffalo Chicken'), ('BarbecueChicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('BlackOlives', 'Black Olives'), ('FreshGarlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, through='orders.OrderDetail', to='orders.MenuItem'),
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('SM', 'Small'), ('LG', 'Large')], max_length=2)),
                ('extraCheese', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem')),
                ('orderDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDetail')),
                ('sandwichToppings', models.ManyToManyField(blank=True, to='orders.CheesesteakTopping')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.PizzaTopping')),
            ],
        ),
    ]
