# Generated by Django 3.0.6 on 2020-05-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, to='orders.GeneralMenuItem')),
            ],
        ),
    ]
