# Generated by Django 3.0.6 on 2020-05-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='specialInstructions',
            new_name='notes',
        ),
    ]
