# Generated by Django 3.0.6 on 2020-05-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200511_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorderdetail',
            name='item',
        ),
    ]
