# Generated by Django 3.0.6 on 2020-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('size', models.CharField(choices=[('NA', 'N/A'), ('SM', 'Small'), ('LG', 'Large')], default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='menuItem',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
