# Generated by Django 3.0.6 on 2020-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='extraCheese',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
