# Generated by Django 3.0.6 on 2020-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200524_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='extraCheese',
            field=models.BooleanField(default=False),
        ),
    ]
