# Generated by Django 3.0.6 on 2020-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200527_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
