# Generated by Django 3.0.6 on 2020-05-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200505_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('type', models.CharField(choices=[('NML', 'Normal'), ('SCL', 'Sicilian')], default='NML', max_length=3)),
            ],
            bases=('orders.item',),
        ),
    ]
