# Generated by Django 3.0.6 on 2020-06-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200610_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkedOut',
            field=models.BooleanField(default=False),
        ),
    ]
