# Generated by Django 3.0.6 on 2020-05-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(default='Cheese', max_length=73),
        ),
    ]
