# Generated by Django 3.0.6 on 2020-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('DLY', 'Delivery'), ('PCK', 'Pickup')], max_length=3),
        ),
    ]
