# Generated by Django 3.0.6 on 2020-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
